### ISSUE TITLE
How can i add one of the languages to my site?

### ISSUE THREAD

**Issue by Indoraptor1** [abantecart/abantecart-languages#3]
Hello, 
How can i add the hungarian language to my site? I just need to copy paste with ftp or i need to add it as a plugin? Thanks for the answer

**Comment by BasaraABC** [comment]
Please post your questions in the AbanteCart forum https://forum.abantecart.com/

https://abantecart.atlassian.net/wiki/spaces/AD/pages/15269894/Languages
